name: globe_ai_example
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  globe_ai: ^1.0.0+3
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  test: ^1.24.0
  lints: ^4.0.0
